name: Bump minor version

on:
  workflow_dispatch:
      
permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pip install build
          pip install bumpver
          pip install mkdocs
          pip install mkdocstrings[python]>=0.18
          pip install mkdocs-gen-files
          pip install mkdocs-material
          pip install mkdocs-literate-nav
          pip install Pygments>=2.12
          git checkout -b release
          git merge develop
          bumpver update --minor --no-push
          git push